# Generated by Django 4.2.1 on 2023-05-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('level', models.CharField(max_length=50)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('department', models.CharField(max_length=100)),
                ('active_status', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
