# Generated by Django 4.2.1 on 2023-05-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default='2003-03-30'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='CS', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='kareem@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default='202', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(default='4', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='0123', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='kareem', max_length=255),
        ),
    ]
