# Generated by Django 4.2.1 on 2023-05-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_student_active_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='CS', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='kareem@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='0123', max_length=15, null=True),
        ),
    ]
