# Generated by Django 4.2.1 on 2023-05-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_student_active_status_alter_student_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
