# Generated by Django 4.2.1 on 2023-05-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0005_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=255, null=True)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mobile', models.CharField(default='0123', max_length=15, null=True)),
                ('email', models.EmailField(default='kareem@gmail.com', max_length=254, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('level', models.CharField(max_length=1, null=True)),
                ('gpa', models.DecimalField(decimal_places=2, default=4, max_digits=3, null=True)),
                ('department', models.CharField(default='CS', max_length=100, null=True)),
                ('active_status', models.BooleanField(default=True, null=True)),
                ('gender', models.CharField(default=True, max_length=10, null=True)),
            ],
        ),
    ]
