# Generated by Django 4.2.1 on 2023-05-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('studname', models.CharField(max_length=255, null=True)),
                ('studid', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
