# Generated by Django 4.2.1 on 2023-05-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_stud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stud',
        ),
    ]
